spring.application.name=eady

spring.datasource.url = jdbc:mysql://localhost:3309/eady_db
spring.datasource.username = user
spring.datasource.password = 1234

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true